//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientInformation
    {
        public int Id { get; set; }
        public int ClientId { get; set; }
        public string BankName { get; set; }
        public int BankCode { get; set; }
        public Nullable<int> BranchBankCode { get; set; }
        public string AccountName { get; set; }
        public string AccountNo { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ClientData ClientData { get; set; }
    }
}
